FROM golang:1.20 AS builder

WORKDIR /app

COPY go.mod hello.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o hello hello.go

FROM scratch

COPY --from=builder /app/hello .

CMD ["./hello"]